-- **************************************************************************
-- * FarmBuddyConst.lua
-- *
-- * By: Keldor
-- **************************************************************************

-- Addon information
FARM_BUDDY_ID = 'FarmBuddyStandalone'
FARM_BUDDY_ADDON_NAME = 'Farm Buddy'

-- Colors
FARM_BUDDY_COLOR_WHITE = 'FFFFFFFF'
FARM_BUDDY_COLOR_YELLOW = 'FFFFFF00'
FARM_BUDDY_COLOR_GREEN = 'FF00FF00'
FARM_BUDDY_COLOR_ORANGE = 'FFFFD300'
FARM_BUDDY_COLOR_RED = 'FFFF0000'

-- Dialogs
FARM_BUDDY_DIALOG_SET_ITEM_GOAL = 'FARM_BUDDY_DIALOG_SET_ITEM_GOAL'
FARM_BUDDY_DIALOG_RESET_ALL_ITEMS_CONFIRM = 'FARM_BUDDY_DIALOG_RESET_ALL_ITEMS_CONFIRM'
FARM_BUDDY_DIALOG_RESET_ALL_CONFIRM = 'FARM_BUDDY_DIALOG_RESET_ALL_CONFIRM'
FARM_BUDDY_DIALOG_RESET_FRAME_POSITION_CONFIRM = 'FARM_BUDDY_DIALOG_RESET_FRAME_POSITION_CONFIRM'
